version: '3'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-log:
    name: foo-emqx-log

services:
  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
    ports:
      - "80:80"
      - "443:443"
      - "1884:1883"
      - "8084:8084"
      - "8883:8883"
      - "8082:8081"
      
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf      
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/modules-enabled:/etc/nginx/modules-enabled
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot 
      - ./html:/app/html:ro

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot


  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    restart: always

    expose:
      - 18083
      - 1883
      - 8083
      - 8081

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-log:/opt/emqx/log
    
    environment:
      EMQX_NAME: savecontrol
      EMQX_HOST: 127.0.0.1

      TZ: "${TZ}"

      # DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_DEFAULT_USER_PASSWORD}"

      # DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_DEFAULT_APPLICATION_SECRET}"

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      # MONGO CONNECTION

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000

